name: CordCloud

on:
  schedule:
    # - cron: "* * * * *" # per 5 minutes
    - cron: "0 0 10,15,20 * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
          host: cordcloud.one,cordcloud.us,cordcloud.biz,c-cloud.xyz
